### ISSUE TITLE
Don't commit node_modules, commit built action code instead

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-percy#37]
Stop including the `node_modules` directory in version control. Instead create a bundle using `ncc`, and point to the built file in the `package.json` `main` property. The same as [was done for `origami-version`](https://github.com/Financial-Times/origami-version/pull/100).

There is an issue with the `origami-version` approach related to automated releases. To complete this issue we need to either [figure out a method for making a commit on release, within our build steps](https://github.com/Financial-Times/origami/pull/111) or manually commit built assets before each release.

**Comment by JakeChampion** [comment]
> To include `origami-build-tools` as a dependency, without committing its codebase as part of node_modules, update `origami-percy` to commit a build copy of the action on release.

I don't understand what this means, could you expand on "update `origami-percy` to commit a build copy of the action on release"?

**Comment by notlee** [comment]
@JakeChampion I've updated the description which is hopefully more clear

**Comment by JakeChampion** [comment]
> Stop including the `node_modules` directory in version control. Instead create a bundle using `ncc`, and point to the built file in the `package.json` `main` property. The same as [was done for `origami-version`](https://github.com/Financial-Times/origami-version/pull/100).

Unfortunately this won't work for this github action because it uses a command-line dependency (origami-build-tools) which will not get included in the bundled code.

What we would need to do to enable bundling to work for this action is to extract the origami-build-tools commands into a non-command-line API. origami-build-tools used to have a programmatic/library/non-command-line API but we removed it because we no longer supported that use-case.

**Comment by JakeChampion** [comment]
I've spoken to Lee about this, we don't think this work is worth the effort. I'll close this now 👍
